# nixpacks.toml

# Fase de configuración: da permisos de ejecución al binario de PocketBase
[phases.setup]
commands = ["chmod +x /app/pocketbase"]


# Fase de inicio: el comando para iniciar PocketBase
[phases.start]
commands = ["/app/pocketbase serve --http 0.0.0.0:${PORT}"]

# Variables de entorno para configurar el puerto
[environment]
PORT = "8090"

# Dependencias: Si es necesario, puedes agregar paquetes adicionales aquí
[dependencies]
packages = []

# Definir el puerto que se expondrá (especificamos el puerto para Railway)
EXPOSE_PORT = "8090"
